# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: factory.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='factory.proto',
  package='factory',
  serialized_pb=_b('\n\rfactory.proto\x12\x07\x66\x61\x63tory\"\x16\n\x06\x63hild1\x12\x0c\n\x04name\x18\x01 \x02(\t\"\x16\n\x06\x63hild2\x12\x0c\n\x04name\x18\x01 \x02(\t\"\x16\n\x06\x63hild3\x12\x0c\n\x04name\x18\x01 \x02(\t\"q\n\x03\x64oc\x12\"\n\tchildren1\x18\x01 \x03(\x0b\x32\x0f.factory.child1\x12\"\n\tchildren2\x18\x02 \x03(\x0b\x32\x0f.factory.child2\x12\"\n\tchildren3\x18\x03 \x03(\x0b\x32\x0f.factory.child3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_CHILD1 = _descriptor.Descriptor(
  name='child1',
  full_name='factory.child1',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='factory.child1.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=48,
)


_CHILD2 = _descriptor.Descriptor(
  name='child2',
  full_name='factory.child2',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='factory.child2.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=50,
  serialized_end=72,
)


_CHILD3 = _descriptor.Descriptor(
  name='child3',
  full_name='factory.child3',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='factory.child3.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=74,
  serialized_end=96,
)


_DOC = _descriptor.Descriptor(
  name='doc',
  full_name='factory.doc',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='children1', full_name='factory.doc.children1', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='children2', full_name='factory.doc.children2', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='children3', full_name='factory.doc.children3', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=98,
  serialized_end=211,
)

_DOC.fields_by_name['children1'].message_type = _CHILD1
_DOC.fields_by_name['children2'].message_type = _CHILD2
_DOC.fields_by_name['children3'].message_type = _CHILD3
DESCRIPTOR.message_types_by_name['child1'] = _CHILD1
DESCRIPTOR.message_types_by_name['child2'] = _CHILD2
DESCRIPTOR.message_types_by_name['child3'] = _CHILD3
DESCRIPTOR.message_types_by_name['doc'] = _DOC

child1 = _reflection.GeneratedProtocolMessageType('child1', (_message.Message,), dict(
  DESCRIPTOR = _CHILD1,
  __module__ = 'factory_pb2'
  # @@protoc_insertion_point(class_scope:factory.child1)
  ))
_sym_db.RegisterMessage(child1)

child2 = _reflection.GeneratedProtocolMessageType('child2', (_message.Message,), dict(
  DESCRIPTOR = _CHILD2,
  __module__ = 'factory_pb2'
  # @@protoc_insertion_point(class_scope:factory.child2)
  ))
_sym_db.RegisterMessage(child2)

child3 = _reflection.GeneratedProtocolMessageType('child3', (_message.Message,), dict(
  DESCRIPTOR = _CHILD3,
  __module__ = 'factory_pb2'
  # @@protoc_insertion_point(class_scope:factory.child3)
  ))
_sym_db.RegisterMessage(child3)

doc = _reflection.GeneratedProtocolMessageType('doc', (_message.Message,), dict(
  DESCRIPTOR = _DOC,
  __module__ = 'factory_pb2'
  # @@protoc_insertion_point(class_scope:factory.doc)
  ))
_sym_db.RegisterMessage(doc)


# @@protoc_insertion_point(module_scope)
